apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: webshop
  labels:
    app: webshop
    component: mongodb
spec:
  selector:
    app: webshop
    component: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None 
