apiVersion: v1
kind: Service
metadata:
  name: jaeger-headless
  namespace: webshop
  labels:
    app: webshop
    component: jaeger
spec:
  clusterIP: None
  selector:
    app: webshop
    component: jaeger
  ports:
  - name: jaeger-ui
    port: 16686
    targetPort: 16686
  - name: jaeger-agent
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
